# Multiple Linear Regression

## Importing the libraries

In [112]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [150]:
dataset=pd.read_csv("50_Startups.csv")
X = dataset.iloc[:, 0:3].values
Y= dataset.iloc[:,4].values
X,Y

(array([[165349.2 , 136897.8 , 471784.1 ],
        [162597.7 , 151377.59, 443898.53],
        [153441.51, 101145.55, 407934.54],
        [144372.41, 118671.85, 383199.62],
        [142107.34,  91391.77, 366168.42],
        [131876.9 ,  99814.71, 362861.36],
        [134615.46, 147198.87, 127716.82],
        [130298.13, 145530.06, 323876.68],
        [120542.52, 148718.95, 311613.29],
        [123334.88, 108679.17, 304981.62],
        [101913.08, 110594.11, 229160.95],
        [100671.96,  91790.61, 249744.55],
        [ 93863.75, 127320.38, 249839.44],
        [ 91992.39, 135495.07, 252664.93],
        [119943.24, 156547.42, 256512.92],
        [114523.61, 122616.84, 261776.23],
        [ 78013.11, 121597.55, 264346.06],
        [ 94657.16, 145077.58, 282574.31],
        [ 91749.16, 114175.79, 294919.57],
        [ 86419.7 , 153514.11,      0.  ],
        [ 76253.86, 113867.3 , 298664.47],
        [ 78389.47, 153773.43, 299737.29],
        [ 73994.56, 122782.75, 303319.26],
        [ 6

## Splitting the dataset into the Training set and Test set

In [154]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.3, random_state = 0)
X_train, X_test, y_train, y_test

(array([[130298.13, 145530.06, 323876.68],
        [119943.24, 156547.42, 256512.92],
        [  1000.23, 124153.04,   1903.93],
        [   542.05,  51743.15,      0.  ],
        [ 65605.48, 153032.06, 107138.38],
        [114523.61, 122616.84, 261776.23],
        [ 61994.48, 115641.28,  91131.24],
        [ 63408.86, 129219.61,  46085.25],
        [ 78013.11, 121597.55, 264346.06],
        [ 23640.93,  96189.63, 148001.11],
        [ 76253.86, 113867.3 , 298664.47],
        [ 15505.73, 127382.3 ,  35534.17],
        [120542.52, 148718.95, 311613.29],
        [ 91992.39, 135495.07, 252664.93],
        [ 64664.71, 139553.16, 137962.62],
        [131876.9 ,  99814.71, 362861.36],
        [ 94657.16, 145077.58, 282574.31],
        [ 28754.33, 118546.05, 172795.67],
        [     0.  , 116983.8 ,  45173.06],
        [162597.7 , 151377.59, 443898.53],
        [ 93863.75, 127320.38, 249839.44],
        [ 44069.95,  51283.14, 197029.42],
        [ 77044.01,  99281.34, 140574.81],
        [13

## Training the Multiple Linear Regression model on the Training set

In [157]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

## Predicting the Test set results

In [143]:
y_pred = regressor.predict(X_test)
y_pred


array([104054.44293869, 132719.3459701 , 133640.26830949,  72294.76911458,
       179685.62227843, 114508.97572031,  66305.23069863,  98297.69326565,
       114277.91894933, 169112.36095691,  96257.40152149,  87916.97242208,
       110687.33942598,  90670.8337806 , 127780.63539583])

In [ ]:
# Get the statistics / description of model
# to get the complete statistics of model we need
# to use statsmodels library

In [159]:
import statsmodels.api as sm
X_train = sm.add_constant(X_train)
model = sm.OLS(y_train, X_train).fit()
model.summary2().tables[1]['P>|t|']



x1    1.668129e-11
x2    1.080926e-11
x3    1.132094e-02
Name: P>|t|, dtype: float64

In [162]:
# Step 1: Add a constant column for the intercept term
X_train = sm.add_constant(X_train)

# Step 2: Fit the initial model with all independent variables
model = sm.OLS(y_train, X_train).fit()

# Step 3: Perform backward elimination
while True:
    # Step 3a: Get the p-values for each coefficient
    p_values = model.pvalues[1:]  # Exclude the constant term
    
    # Step 3b: Find the variable with the highest p-value
    max_p_value = max(p_values)
    if max_p_value > 0.05:  # Set your significance level (e.g., 0.05)
        # Step 3c: Remove the variable with the highest p-value
        variable_to_remove = np.argmax(p_values) + 1
        X_train = np.delete(X_train, variable_to_remove, axis=1)
        model = sm.OLS(y_train, X_train).fit()
    else:
        break

# Step 4: Print the final model summary
model.summary2().tables[1]

Coef.     Std.Err.          t         P>|t|        [0.025  \
const  47660.729270  3080.344936  15.472530  1.097298e-16  41393.720377   
x1         0.858217     0.035115  24.439867  1.030995e-22      0.786774   

             0.975]  
const  53927.738163  
x1         0.929660