# Logistic Regression

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv(r'C:\Users\AYUSH\OneDrive\Desktop\Machine Learning\Assignment 18.ipynb\fitness_class_2212 - fitness_class_2212 (1).csv')
dataset

booking_id  months_as_member  weight days_before day_of_week time  \
0              1                17   79.56           8         Wed   PM   
1              2                10   79.01           2         Mon   AM   
2              3                16   74.53          14         Sun   AM   
3              4                 5   86.12          10         Fri   AM   
4              5                15   69.29           8         Thu   AM   
...          ...               ...     ...         ...         ...  ...   
1495        1496                21   79.51          10         Fri   AM   
1496        1497                29   89.55           2         Mon   AM   
1497        1498                 9   87.38           4         Tue   AM   
1498        1499                34   68.64          14         Sun   AM   
1499        1500                20   94.39           8         Thu   AM   

      category  attended  
0     Strength         0  
1         HIIT         0  
2     Strength         0  
3      Cycling         0  
4         HIIT         0  
...        ...       ...  
1495      HIIT         0  
1496  Strength         0  
1497      HIIT         0  
1498      Aqua         0  
1499   Cycling         1  

[1500 rows x 8 columns]

In [3]:
X = dataset.iloc[:, [-1, 1]].values
y = dataset.iloc[:, [7]].values
X,y


(array([[ 0, 17],
        [ 0, 10],
        [ 0, 16],
        ...,
        [ 0,  9],
        [ 0, 34],
        [ 1, 20]], dtype=int64),
 array([[0],
        [0],
        [0],
        ...,
        [0],
        [0],
        [1]], dtype=int64))

## Splitting the dataset into the Training set and Test set

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [5]:
print(X_train)

[[ 0 12]
 [ 0 12]
 [ 0  6]
 ...
 [ 0  4]
 [ 0  8]
 [ 1 24]]


In [6]:
print(y_train)

[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [1]]


In [7]:
print(X_test)

[[  0   5]
 [  0   7]
 [  1  20]
 [  1  53]
 [  0  32]
 [  1  38]
 [  0   9]
 [  0  32]
 [  0  15]
 [  0   6]
 [  1  11]
 [  0   5]
 [  0  11]
 [  0  34]
 [  0  31]
 [  0  19]
 [  0  12]
 [  0   5]
 [  0   8]
 [  0   4]
 [  0   6]
 [  0   6]
 [  0   6]
 [  0  11]
 [  1  30]
 [  1  23]
 [  0  13]
 [  1  21]
 [  0   8]
 [  0  13]
 [  0  10]
 [  0   5]
 [  0  26]
 [  1  32]
 [  1  16]
 [  0   6]
 [  1  18]
 [  1  11]
 [  0  17]
 [  0  15]
 [  1  38]
 [  1  25]
 [  0   9]
 [  0  22]
 [  0   7]
 [  0   6]
 [  1  12]
 [  1   7]
 [  0  12]
 [  1  38]
 [  0   9]
 [  1  11]
 [  0   5]
 [  1  24]
 [  1  22]
 [  1  16]
 [  0   4]
 [  0  14]
 [  0   9]
 [  0  15]
 [  0  21]
 [  0  11]
 [  1  16]
 [  1  48]
 [  1  31]
 [  0  13]
 [  0   6]
 [  0  18]
 [  1  58]
 [  0   5]
 [  1  33]
 [  0   9]
 [  0  13]
 [  0  18]
 [  1  21]
 [  0  30]
 [  0   9]
 [  0  16]
 [  1  29]
 [  0   4]
 [  0  12]
 [  0  21]
 [  1  10]
 [  0   9]
 [  0  16]
 [  0   3]
 [  1  18]
 [  0  10]
 [  1  18]
 [  0  20]
 [  0   8]

In [8]:
print(y_test)

[[0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]


## Feature Scaling

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:
print(X_train)

[[-0.64842466 -0.27189722]
 [-0.64842466 -0.27189722]
 [-0.64842466 -0.73141305]
 ...
 [-0.64842466 -0.884585  ]
 [-0.64842466 -0.57824111]
 [ 1.5421992   0.64713444]]


In [11]:
print(X_test)

[[-0.64842466 -0.80799902]
 [-0.64842466 -0.65482708]
 [ 1.5421992   0.34079056]
 [ 1.5421992   2.86812763]
 [-0.64842466  1.25982222]
 [ 1.5421992   1.71933805]
 [-0.64842466 -0.50165514]
 [-0.64842466  1.25982222]
 [-0.64842466 -0.0421393 ]
 [-0.64842466 -0.73141305]
 [ 1.5421992  -0.34848319]
 [-0.64842466 -0.80799902]
 [-0.64842466 -0.34848319]
 [-0.64842466  1.41299416]
 [-0.64842466  1.18323625]
 [-0.64842466  0.26420458]
 [-0.64842466 -0.27189722]
 [-0.64842466 -0.80799902]
 [-0.64842466 -0.57824111]
 [-0.64842466 -0.884585  ]
 [-0.64842466 -0.73141305]
 [-0.64842466 -0.73141305]
 [-0.64842466 -0.73141305]
 [-0.64842466 -0.34848319]
 [ 1.5421992   1.10665028]
 [ 1.5421992   0.57054847]
 [-0.64842466 -0.19531125]
 [ 1.5421992   0.41737653]
 [-0.64842466 -0.57824111]
 [-0.64842466 -0.19531125]
 [-0.64842466 -0.42506916]
 [-0.64842466 -0.80799902]
 [-0.64842466  0.80030639]
 [ 1.5421992   1.25982222]
 [ 1.5421992   0.03444667]
 [-0.64842466 -0.73141305]
 [ 1.5421992   0.18761861]
 

## Training the Logistic Regression model on the Training set

In [12]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

C:\Users\ashwa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(random_state=0)

## Predicting a new result

In [13]:
print(classifier.predict(sc.transform([[30,87000]])))

[1]


## Predicting the Test set results

In [14]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]

# Accuracy measures

In [15]:
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, accuracy_score
# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

# Precision
precision = precision_score(y_test, y_pred)
print("\nPrecision:", precision)

# Recall
recall = recall_score(y_test, y_pred)
print("Recall:", recall)

# F1 Score
f1 = f1_score(y_test, y_pred)
print("F1 Score:", f1)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Confusion Matrix:
[[254   0]
 [  0 121]]

Precision: 1.0
Recall: 1.0
F1 Score: 1.0
Accuracy: 1.0
