In [35]:
import pandas as pd

In [2]:
df=pd.read_csv("Int_ad.csv")

In [3]:
df

Name  cgpa  \
0     Ram Vardhan Ramraj  8.51   
1        Atharva Pradhan  9.43   
2           Yash Paliwal  8.20   
3     Kaustubh Kothawale  8.84   
4            Suraj Sunke  6.65   
...                  ...   ...   
1224      Vinutha Ananth  9.00   
1225     Aditya Varshney  8.30   
1226       Abhinav Singh  8.27   
1227     Parth Mandaliya  7.57   
1228        Ajay Krishna  8.04   

                                                 course  WorkExp(Months)  \
0     Arizona State University - Tempe - Computer Sc...                0   
1     Arizona State University - Tempe - Robotics an...                0   
2     Arizona State University - Tempe - Robotics an...                3   
3     Arizona State University - Tempe - Computer Sc...               34   
4     Arizona State University - Tempe - Information...               12   
...                                                 ...              ...   
1224    University of Texas - Austin - Computer Science               40   
1225  University of Texas - Austin - Computer Engine...               28   
1226  University of Texas - Austin - Business Analytics               33   
1227    University of Texas - Austin - Computer Science               29   
1228            University of Texas - Austin - Business               15   

      WorkExp(Years)  research  QUANT  VERBAL  AWA  GRE  SPEAKING  Listening  \
0                0.0         1    161     143  3.5  304        28         26   
1                0.0         0    167     144  3.5  311        26         29   
2                0.3         0    169     160  3.0  329        23         28   
3                2.1         0    167     148  1.5  315        24         26   
4                1.0         0    166     152  2.5  318        24         22   
...              ...       ...    ...     ...  ...  ...       ...        ...   
1224             3.4         0    150     155  4.0  305        29         30   
1225             2.4         0    164     151  3.0  315        27         29   
1226             2.9         0    170     157  3.0  327        25         28   
1227             2.5         0    160     170  5.0  330        25         25   
1228             1.3         0    165     155  5.0  320        27         27   

      Writing  Reading  TOEFL_IELTS admit_reject  
0          22       24          100        admit  
1          25       27          107        admit  
2          21       25           97        admit  
3          26       27          103        admit  
4          21       21           88        admit  
...       ...      ...          ...          ...  
1224       28       28          115       reject  
1225       26       25          107       reject  
1226       24       30          107       reject  
1227       25       25          100        admit  
1228       27       30          111        admit  

[1229 rows x 16 columns]

In [5]:
df.head(10)

Name  cgpa  \
0  Ram Vardhan Ramraj  8.51   
1     Atharva Pradhan  9.43   
2        Yash Paliwal  8.20   
3  Kaustubh Kothawale  8.84   
4         Suraj Sunke  6.65   
5       Rohit Krishna  8.65   
6         Arshak Shan  8.87   
7        Subham Kumar  8.51   
8        Subham Kumar  8.51   
9        Kathan Desai  8.70   

                                              course  WorkExp(Months)  \
0  Arizona State University - Tempe - Computer Sc...                0   
1  Arizona State University - Tempe - Robotics an...                0   
2  Arizona State University - Tempe - Robotics an...                3   
3  Arizona State University - Tempe - Computer Sc...               34   
4  Arizona State University - Tempe - Information...               12   
5  Arizona State University - Tempe - Computer Sc...                0   
6  Arizona State University - Tempe - Software En...                8   
7  Arizona State University - Tempe - Software En...               60   
8  Arizona State University - Tempe - Computer Sc...               60   
9  Arizona State University - Tempe - Chemical En...                0   

   WorkExp(Years)  research  QUANT  VERBAL  AWA  GRE  SPEAKING  Listening  \
0             0.0         1    161     143  3.5  304        28         26   
1             0.0         0    167     144  3.5  311        26         29   
2             0.3         0    169     160  3.0  329        23         28   
3             2.1         0    167     148  1.5  315        24         26   
4             1.0         0    166     152  2.5  318        24         22   
5             0.0         0    164     152  3.5  316        25         24   
6             0.8         1    163     154  4.5  317        26         28   
7             5.0         0    163     152  3.5  315        24         26   
8             5.0         0    163     152  3.5  315        24         26   
9             0.0         0    162     152  3.0  314        23         30   

   Writing  Reading  TOEFL_IELTS admit_reject  
0       22       24          100        admit  
1       25       27          107        admit  
2       21       25           97        admit  
3       26       27          103        admit  
4       21       21           88        admit  
5       25       30          104        admit  
6       30       25          109        admit  
7       24       26          100        admit  
8       24       26          100       reject  
9       24       24          101        admit

In [6]:
df.tail()

Name  cgpa  \
1224   Vinutha Ananth  9.00   
1225  Aditya Varshney  8.30   
1226    Abhinav Singh  8.27   
1227  Parth Mandaliya  7.57   
1228     Ajay Krishna  8.04   

                                                 course  WorkExp(Months)  \
1224    University of Texas - Austin - Computer Science               40   
1225  University of Texas - Austin - Computer Engine...               28   
1226  University of Texas - Austin - Business Analytics               33   
1227    University of Texas - Austin - Computer Science               29   
1228            University of Texas - Austin - Business               15   

      WorkExp(Years)  research  QUANT  VERBAL  AWA  GRE  SPEAKING  Listening  \
1224             3.4         0    150     155  4.0  305        29         30   
1225             2.4         0    164     151  3.0  315        27         29   
1226             2.9         0    170     157  3.0  327        25         28   
1227             2.5         0    160     170  5.0  330        25         25   
1228             1.3         0    165     155  5.0  320        27         27   

      Writing  Reading  TOEFL_IELTS admit_reject  
1224       28       28          115       reject  
1225       26       25          107       reject  
1226       24       30          107       reject  
1227       25       25          100        admit  
1228       27       30          111        admit

In [9]:
size=df.size

In [10]:
size

19664

In [11]:
df.shape

(1229, 16)

In [12]:
df.ndim

2

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1229 entries, 0 to 1228
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Name             1229 non-null   object 
 1   cgpa             1229 non-null   float64
 2   course           1229 non-null   object 
 3   WorkExp(Months)  1229 non-null   int64  
 4   WorkExp(Years)   1229 non-null   float64
 5   research         1229 non-null   int64  
 6   QUANT            1229 non-null   int64  
 7   VERBAL           1229 non-null   int64  
 8   AWA              1229 non-null   float64
 9   GRE              1229 non-null   int64  
 10  SPEAKING         1229 non-null   int64  
 11  Listening        1229 non-null   int64  
 12  Writing          1229 non-null   int64  
 13  Reading          1229 non-null   int64  
 14  TOEFL_IELTS      1229 non-null   int64  
 15  admit_reject     1229 non-null   object 
dtypes: float64(3), int64(10), object(3)
memory usage: 153.8+ KB


In [14]:
df.describe()

cgpa  WorkExp(Months)  WorkExp(Years)     research        QUANT  \
count  1229.000000      1229.000000     1229.000000  1229.000000  1229.000000   
mean      8.305989        15.314076        1.282815     0.887714   162.856794   
std       0.900189        17.070050        1.418444     1.461923     5.155307   
min       3.100000         0.000000        0.000000     0.000000   130.000000   
25%       7.750000         2.000000        0.100000     0.000000   160.000000   
50%       8.400000         9.000000        0.700000     0.000000   164.000000   
75%       8.970000        24.000000        2.000000     1.000000   167.000000   
max       9.950000       104.000000        8.800000    14.000000   170.000000   

            VERBAL          AWA          GRE     SPEAKING    Listening  \
count  1229.000000  1229.000000  1229.000000  1229.000000  1229.000000   
mean    151.380797     3.702604   314.237592    24.826688    26.750203   
std       5.895658     0.618032     9.295485     2.816899     2.679746   
min     130.000000     0.000000   260.000000     2.000000    15.000000   
25%     147.000000     3.500000   308.000000    23.000000    25.000000   
50%     152.000000     3.500000   314.000000    25.000000    27.000000   
75%     155.000000     4.000000   320.000000    27.000000    29.000000   
max     170.000000     5.500000   336.000000    30.000000    30.000000   

           Writing      Reading  TOEFL_IELTS  
count  1229.000000  1229.000000  1229.000000  
mean     25.483320    26.366965   103.427177  
std       2.906091     2.883952     8.043486  
min       0.000000    15.000000    56.000000  
25%      24.000000    25.000000    98.000000  
50%      26.000000    27.000000   104.000000  
75%      28.000000    29.000000   109.000000  
max      30.000000    30.000000   120.000000

# Lable Encoding

In [15]:
df1=pd.read_csv("Iris.csv")

In [16]:
df1.shape

(150, 6)

In [19]:
df1.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [23]:
df1['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [25]:

# Import label encoder
from sklearn import preprocessing
  
# label_encoder object knows 
# how to understand word labels.
label_encoder = preprocessing.LabelEncoder()
  
# Encode labels in column 'species'.
df1['Species']= label_encoder.fit_transform(df1['Species'])
  
df1['Species'].unique()

array([0, 1, 2], dtype=int64)

# One hot encoding

In [27]:
df['admit_reject'].unique()

array(['admit', 'reject'], dtype=object)

In [28]:
df['admit_reject'].value_counts()

admit     871
reject    358
Name: admit_reject, dtype: int64

In [29]:
one_hot_encoded_data = pd.get_dummies(df, columns = ['admit_reject'])

In [30]:
print(one_hot_encoded_data)

                    Name  cgpa  \
0     Ram Vardhan Ramraj  8.51   
1        Atharva Pradhan  9.43   
2           Yash Paliwal  8.20   
3     Kaustubh Kothawale  8.84   
4            Suraj Sunke  6.65   
...                  ...   ...   
1224      Vinutha Ananth  9.00   
1225     Aditya Varshney  8.30   
1226       Abhinav Singh  8.27   
1227     Parth Mandaliya  7.57   
1228        Ajay Krishna  8.04   

                                                 course  WorkExp(Months)  \
0     Arizona State University - Tempe - Computer Sc...                0   
1     Arizona State University - Tempe - Robotics an...                0   
2     Arizona State University - Tempe - Robotics an...                3   
3     Arizona State University - Tempe - Computer Sc...               34   
4     Arizona State University - Tempe - Information...               12   
...                                                 ...              ...   
1224    University of Texas - Austin - Computer Science    

In [32]:
print(one_hot_encoded_data['admit_reject_admit'])

0       1
1       1
2       1
3       1
4       1
       ..
1224    0
1225    0
1226    0
1227    1
1228    1
Name: admit_reject_admit, Length: 1229, dtype: uint8


In [33]:
print(one_hot_encoded_data['admit_reject_reject'])

0       0
1       0
2       0
3       0
4       0
       ..
1224    1
1225    1
1226    1
1227    0
1228    0
Name: admit_reject_reject, Length: 1229, dtype: uint8


In [34]:
from numpy import array  
from numpy import argmax  
from sklearn.preprocessing import LabelEncoder  
from sklearn.preprocessing import OneHotEncoder  
# defining sequence example  
data_1 = ['apple', 'apple', 'mango', 'apple', 'banana', 'banana', 'mango', 'apple']  
values_of_seq = array(data_1)  
print(values_of_seq)  
# first appling integer encode  
label_encoder = LabelEncoder()  
integer_encoded = label_encoder.fit_transform(values_of_seq)  
print(integer_encoded)  
# Now doing binary encode  
onehot_encoder = OneHotEncoder(sparse=False)  
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)  
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)  
print(onehot_encoded)  

['apple' 'apple' 'mango' 'apple' 'banana' 'banana' 'mango' 'apple']
[0 0 2 0 1 1 2 0]
[[1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [ ]:
import matplotlib.pyplot as plt
df.plot(kind = 'bar')