In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import Lasso
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [2]:
data=pd.read_csv("house_price_corl.csv")
data

Square Feet  Bedrooms  Bathrooms  Garage Size   House Price
0   2195.254016  5.068325   1.409423     2.719666  6.736767e+05
1   2860.757465  5.991523   2.126722     2.322142  8.565531e+05
2   2411.053504  5.557301   1.583279     0.999435  7.219910e+05
3   2179.532732  5.321254   1.269370     0.243304  6.766694e+05
4   1694.619197  3.637992   0.871988     1.221724  4.867076e+05
..          ...       ...        ...          ...           ...
95   732.765448  1.955990   0.590700     2.876948  2.274353e+05
96  2346.051739  4.919518   1.270870     1.066107  6.696193e+05
97    80.430185  0.415217   0.902407     1.070121  3.145710e+04
98  3315.760117  6.689549   2.630800     0.048986  1.012751e+06
99    18.781905  0.471980   0.970226     0.555697  7.053013e+03

[100 rows x 5 columns]

In [12]:
X = data.iloc[:,0:3].values
Y= data.iloc[:,3].values
X,Y

(array([[2.19525402e+03, 5.06832457e+00, 1.40942289e+00],
        [2.86075747e+03, 5.99152290e+00, 2.12672222e+00],
        [2.41105350e+03, 5.55730103e+00, 1.58327859e+00],
        [2.17953273e+03, 5.32125401e+00, 1.26937004e+00],
        [1.69461920e+03, 3.63799154e+00, 8.71988327e-01],
        [2.58357645e+03, 5.74331024e+00, 1.35903786e+00],
        [1.75034885e+03, 4.09273962e+00, 1.55456720e+00],
        [3.56709200e+03, 7.70643591e+00, 2.23724285e+00],
        [3.85465104e+03, 7.93238372e+00, 2.46390473e+00],
        [1.53376608e+03, 4.02028116e+00, 1.66355433e+00],
        [3.16690015e+03, 6.78092568e+00, 2.57378902e+00],
        [2.11557968e+03, 5.07756803e+00, 1.27468682e+00],
        [2.27217824e+03, 5.24383576e+00, 1.79916733e+00],
        [3.70238655e+03, 7.70221006e+00, 2.11451565e+00],
        [2.84144233e+02, 1.38208629e+00, 1.62723116e-01],
        [3.48517199e+02, 1.09354014e+00, 9.32637253e-01],
        [8.08735898e+01, 1.04285038e+00, 3.60453946e-01],
        [3.330

In [13]:
# Split the data into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)
X_train, X_test, Y_train, Y_test

(array([[2.40901887e+02, 1.37372713e+00, 2.52519050e-01],
        [2.62531836e+03, 5.97269232e+00, 1.32908881e+00],
        [2.17953273e+03, 5.32125401e+00, 1.26937004e+00],
        [1.87460481e+03, 3.80354760e+00, 1.81380765e+00],
        [2.68255148e+03, 6.06899154e+00, 1.73733544e+00],
        [1.26171340e+03, 3.23766811e+00, 7.75704461e-01],
        [1.75034885e+03, 4.09273962e+00, 1.55456720e+00],
        [1.87819048e+01, 4.71980435e-01, 9.70225610e-01],
        [2.56589985e+02, 1.09040856e+00, 7.46171685e-01],
        [1.13122785e+03, 2.60780738e+00, 1.50699163e+00],
        [6.35878335e+02, 1.96918544e+00, 5.58767947e-01],
        [1.27193272e+03, 2.70855959e+00, 9.28986643e-01],
        [1.27427581e+03, 2.94677268e+00, 1.00572251e+00],
        [3.35177963e+03, 7.43354982e+00, 1.73984508e+00],
        [1.75440605e+03, 4.37693817e+00, 1.81763497e+00],
        [3.77867567e+03, 7.85892615e+00, 2.10484551e+00],
        [3.11262700e+03, 7.10698937e+00, 2.14463062e+00],
        [2.612

In [14]:
from sklearn.linear_model import Lasso
# Step 3: Perform lasso regression with different alpha values
alphas = [0.1, 1.0, 10.0]  # Different values of alpha
for alpha in alphas:
    lasso = Lasso(alpha=alpha)
    lasso.fit(X_train, Y_train)
    Y_pred = lasso.predict(X_test)
    mse = mean_squared_error(Y_test, Y_pred)
    print(f"Alpha = {alpha}, MSE = {mse}")

    # Observe the coefficients for each alpha
    print(f"Coefficients for Alpha = {alpha}: {lasso.coef_}")

Alpha = 0.1, MSE = 0.6862421378943877
Coefficients for Alpha = 0.1: [ 2.35722201e-05 -0.00000000e+00 -0.00000000e+00]
Alpha = 1.0, MSE = 0.6861738500854306
Coefficients for Alpha = 1.0: [ 2.2863523e-05 -0.0000000e+00 -0.0000000e+00]
Alpha = 10.0, MSE = 0.6855793072945173
Coefficients for Alpha = 10.0: [ 1.5776552e-05  0.0000000e+00 -0.0000000e+00]


In [15]:
for alpha in alphas:
    ridge = Lasso(alpha=alpha)
    ridge.fit(X_train, Y_train)
    print(f"Alpha = {alpha}, Coefficients = {ridge.coef_},MSE = {mse}")

Alpha = 0.1, Coefficients = [ 2.35722201e-05 -0.00000000e+00 -0.00000000e+00],MSE = 0.6855793072945173
Alpha = 1.0, Coefficients = [ 2.2863523e-05 -0.0000000e+00 -0.0000000e+00],MSE = 0.6855793072945173
Alpha = 10.0, Coefficients = [ 1.5776552e-05  0.0000000e+00 -0.0000000e+00],MSE = 0.6855793072945173


# sorteddata.csv

In [16]:
data1=pd.read_csv("sorted_data.csv")
data1

R&D Spend  Administration  Marketing Spend        Profit
0   54881.350393    33890.826840      3117.958820  1.505982e+10
1   71518.936637    13500.398660      6963.434888  2.557481e+10
2   60276.337607    36759.701106      3777.518393  1.816618e+10
3   54488.318300    48109.427256      1796.036776  1.484489e+10
4   42365.479934    12437.657176       246.787284  8.974143e+09
..           ...             ...              ...           ...
95  18319.136201    24522.940431      2243.170290  1.677944e+09
96  58651.293481    11370.731399       978.444845  1.719988e+10
97   2010.754619    12717.824089      8621.915174  2.021622e+07
98  82894.002922     2901.458016      9729.194890  3.435708e+10
99    469.547619    21720.831278      9608.346581  1.116819e+06

[100 rows x 4 columns]

In [18]:
x = data1.iloc[:, 0:3].values
y= data1.iloc[:,3].values
x,y

(array([[54881.35039273, 33890.82683981,  3117.95881994],
        [71518.93663724, 13500.39865961,  6963.43488815],
        [60276.33760716, 36759.70110613,  3777.51839292],
        [54488.31829969, 48109.42725587,  1796.0367756 ],
        [42365.47993389, 12437.657176  ,   246.78728391],
        [64589.41130667, 28807.86672089,   672.49631463],
        [43758.72112627, 29602.09656359,  6793.92773499],
        [89177.30007821, 28612.59528954,  4536.96844556],
        [96366.2760501 , 11154.08163203,  5365.79211109],
        [38344.15188258, 47637.45057585,  8966.7129304 ],
        [79172.50380827, 22356.26893088,  9903.38947397],
        [52889.49197529, 42320.43362356,  2168.96984398],
        [56804.45610939, 34973.96376588,  6630.782031  ],
        [92559.66382927, 14871.84754276,  2633.22376737],
        [ 7103.60581979, 40689.89098512,   206.50999466],
        [ 8712.92997015, 19825.28704235,  7583.78653836],
        [ 2021.83974403, 44055.15985556,  3200.17150822],
        [83261

In [21]:
# Split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)
x_train, x_test, y_train, y_test

(array([[ 6022.54716293, 44596.16775078,  1320.68106345],
        [65632.95894653, 36102.77997352,   164.29629591],
        [54488.31829969, 48109.42725587,  1796.0367756 ],
        [46865.12016477,  2716.89941696,  8765.05245317],
        [67063.78696182, 35194.42917702,  3960.59702807],
        [31542.83509242, 35712.06497746,  1448.47759343],
        [43758.72112627, 29602.09656359,  6793.92773499],
        [  469.54761925, 21720.83127791,  9608.34658063],
        [ 6414.74963488, 28861.42943021,  6178.76691918],
        [28280.69625764, 17267.58403485,  9413.77704706],
        [15896.95836455, 34871.43865723,  2408.28779915],
        [31798.3179394 ,  8234.7078249 ,  2930.20284508],
        [31856.89524513, 19911.0531108 ,  3685.8460613 ],
        [83794.49074988, 36499.5281212 ,   639.55266121],
        [43860.15134623, 43406.30286841,  9404.31945253],
        [94466.89170496, 15078.74083373,  2155.07677114],
        [77815.67509499, 44086.76809274,  5883.17113554],
        [65310

In [22]:
from sklearn.linear_model import Lasso
# Step 3: Perform lasso regression with different alpha values
alphas = [0.1, 1.0, 10.0]  # Different values of alpha
for alpha in alphas:
    lasso = Lasso(alpha=alpha)
    lasso.fit(x_train, y_train)
    y_pred = lasso.predict(x_test)
    mse = mean_squared_error(y_test, y_pred)
    print(f"Alpha = {alpha}, MSE = {mse}")

    # Observe the coefficients for each alpha
    print(f"Coefficients for Alpha = {alpha}: {lasso.coef_}")

Alpha = 0.1, MSE = 1.4153427286404014e+19
Coefficients for Alpha = 0.1: [484470.05652233 -40719.27301472  85245.26685542]
Alpha = 1.0, MSE = 1.4153427286403699e+19
Coefficients for Alpha = 1.0: [484470.05652233 -40719.27301472  85245.26685532]
Alpha = 10.0, MSE = 1.4153427286400336e+19
Coefficients for Alpha = 10.0: [484470.05652231 -40719.27301467  85245.26685431]
