In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
# Assuming your dataset file is 'test.csv'
dataset = pd.read_csv(r"/home/infinitex/Desktop/JupiterNotebook/asgn 16/fitness_class_2212 - fitness_class_2212.csv")

# Convert 'days_before' to numeric by removing the ' days' suffix
dataset['days_before'] = dataset['days_before'].str.replace(' days', '').astype(float)

# Check for missing values
print("Missing values in the dataset:")
print(dataset.isnull().sum())

Missing values in the dataset:
booking_id           0
months_as_member     0
weight              20
days_before          0
day_of_week          0
time                 0
category             0
attended             0
dtype: int64


In [11]:
# # Handle missing values by filling with the mean
# dataset.fillna(dataset.mean(), inplace=True)

X = dataset.iloc[:, [1, 2]].values  # Assuming 'months_as_member' is at position 1 and 'weight' is at position 2
y = dataset.iloc[:, -1].values

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

print("X_train:")
print(X_train)
print("\ny_train:")
print(y_train)
print("\nX_test:")
print(X_test)
print("\ny_test:")
print(y_test)

X_train:
[[ 12.    77.03]
 [ 12.    73.33]
 [  6.   100.76]
 ...
 [  4.    83.66]
 [  8.    76.09]
 [ 24.    65.4 ]]

y_train:
[0 0 0 ... 0 0 1]

X_test:
[[  5.   122.36]
 [  7.    81.25]
 [ 20.    94.39]
 [ 53.    61.1 ]
 [ 32.    71.67]
 [ 38.    60.68]
 [  9.    73.8 ]
 [ 32.    84.76]
 [ 15.    76.31]
 [  6.    94.41]
 [ 11.    84.58]
 [  5.   133.36]
 [ 11.    70.18]
 [ 34.    63.41]
 [ 31.    65.71]
 [ 19.    79.35]
 [ 12.    72.82]
 [  5.    99.41]
 [  8.    80.72]
 [  4.   116.17]
 [  6.    82.54]
 [  6.    92.37]
 [  6.   117.19]
 [ 11.    78.65]
 [ 30.    66.24]
 [ 23.    74.79]
 [ 13.   101.34]
 [ 21.    73.59]
 [  8.    99.26]
 [ 13.    83.47]
 [ 10.   102.02]
 [  5.      nan]
 [ 26.    74.59]
 [ 32.    69.71]
 [ 16.    79.54]
 [  6.    85.07]
 [ 18.    93.91]
 [ 11.    78.56]
 [ 17.    82.26]
 [ 15.    81.12]
 [ 38.    82.68]
 [ 25.    68.49]
 [  9.    80.46]
 [ 22.    74.67]
 [  7.   103.46]
 [  6.   104.74]
 [ 12.    60.28]
 [  7.    81.37]
 [ 12.    68.82]
 [ 38.    78.

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

print("\nX_train (after scaling):")
print(X_train)
print("\nX_test (after scaling):")
print(X_test)


X_train (after scaling):
[[-0.27189722 -0.44753589]
 [-0.27189722 -0.73953106]
 [-0.73141305  1.42517904]
 ...
 [-0.884585    0.07568788]
 [-0.57824111 -0.52171845]
 [ 0.64713444 -1.36534772]]

X_test (after scaling):
[[-8.07999024e-01  3.12979946e+00]
 [-6.54827080e-01 -1.14503570e-01]
 [ 3.40790556e-01  9.22473853e-01]
 [ 2.86812763e+00 -1.70469345e+00]
 [ 1.25982222e+00 -8.70534294e-01]
 [ 1.71933805e+00 -1.73783885e+00]
 [-5.01655136e-01 -7.02439780e-01]
 [ 1.25982222e+00  1.62497248e-01]
 [-4.21393037e-02 -5.04356574e-01]
 [-7.31413052e-01  9.24052205e-01]
 [-3.48483192e-01  1.48292078e-01]
 [-8.07999024e-01  3.99789319e+00]
 [-3.48483192e-01 -9.88121536e-01]
 [ 1.41299416e+00 -1.52239377e+00]
 [ 1.18323625e+00 -1.34088326e+00]
 [ 2.64204584e-01 -2.64447033e-01]
 [-2.71897220e-01 -7.79779040e-01]
 [-8.07999024e-01  1.31864027e+00]
 [-5.78241108e-01 -1.56329904e-01]
 [-8.84584996e-01  2.64129944e+00]
 [-7.31413052e-01 -1.26998504e-02]
 [-7.31413052e-01  7.63060276e-01]
 [-7.314130

In [14]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion='entropy', random_state=0)
classifier.fit(X_train, y_train)

# Example prediction
example_prediction = classifier.predict(sc.transform([[17, 79.56]]))
print("\nExample Prediction:")
print(example_prediction)

y_pred = classifier.predict(X_test)
results = np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), axis=1)
print("\nComparison of Predictions and Actual Values:")
print(results)


Example Prediction:
[0]

Comparison of Predictions and Actual Values:
[[1 0]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0